### ISSUE TITLE
status of swift 3 / carthage support

### ISSUE THREAD

**Issue by eliburke** [iscriptology/swamp#4]
I'm curious if you are already working on migrating to Swift 3, have plans to do so, or would accept a PR for same. 

Ditto for Carthage support.

**Comment by wybie-lovat** [comment]
Already got a pending pull request, will be working on that soon!

**Comment by elliottwilliams** [comment]
I'd also be interested in Carthage support. I can attempt to send in a PR in the next couple weeks that adds support.

**Comment by wybie-lovat** [comment]
Swift 3 added, waiting for your Carthage PR! Issue closed
