### ISSUE TITLE
WatchOS support

### ISSUE THREAD

**Issue by aipxperts** [iscriptology/swamp#7]
Hello,

Thanks for such a wonderful library. Can you update your pod specification to provide support for watch os too? Thanks.

**Comment by danysousa** [comment]
Hi ! 
[Starscream](https://github.com/daltoniam/Starscream/blob/master/Starscream.podspec) is not compatible with watchOS, and unfortunately swamp use Starscream.

**Comment by wybie-lovat** [comment]
Closing issue for now, feel free to open a new one once Starscream supports watchOS. (Also I suggest that you open an issue on Starscream github project if you really need this)
