### ISSUE TITLE
Crash when subscribing or calling

### ISSUE THREAD

**Issue by dizialina** [iscriptology/swamp#9]
Hi! I have server with rooms to chat. Full url is ws://93.171.XXX.XX:8080/conversation_realtime/sportspace581a1541590b21.14581077".   
But I have to connect to this by 2 steps:
1) connect to "ws://93.171.XXX.XX:8080"   
2) subscribe to room "conversation_realtime/sportspace581a1541590b21.14581077"

In JS it  looks like:
```
var _WS_URI = "ws://93.171.242.80:8080";
var webSocket = WS.connect(_WS_URI);

webSocket.on("socket/connect", function(session){
session.subscribe("conversation_realtime/sportspace581a1541590b21.14581077", function(uri, payload){
                    console.log(payload.message.text);
}
}
```

When I try to call in my project `swampSession.call("socket/connect"...` or `swampSession.subscribe("conversation_realtime/sportspace581a1541590b21.14581077"....` my app crashes in SwampSession.swift with error "fatal error: unexpectedly found nil while unwrapping an Optional value" in this part:
 ```
fileprivate func sendMessage(_ message: SwampMessage){
        let marshalledMessage = message.marshal()
        let data = self.serializer!.pack(marshalledMessage as [Any])!
        self.transport.sendData(data)
    }
```
How can I realize it in your library? And what is "realm" in my case?

**Comment by danysousa** [comment]
Hi ! 
First, I have a question : are you using a WAMP server like crossbar ?
Because swamp isn't a [faye-websocket-node](https://github.com/hamin/FayeSwift) or [socket.io](https://github.com/socketio/socket.io-client-swift) like, it's an implementation of wamp protocol for client side, if you're not using crossbar or an other implementation, this crash it's normal, and I redirect you to the previous links.

**Comment by dizialina** [comment]
Thx for answer. I tried to write to the most popular libraries with this question, but they said that they don't support any subscribing to channels, just connection to host. And socket.io said "This library isn't a straight websockets library. This is for socket.io servers".  
My server uses [GeniusesOfSymfony/WebSocketBundle](https://github.com/GeniusesOfSymfony/WebSocketBundle) and they advice me "You can use any WAMP v1 client compliant and it will work fine" so I came to you.

**Comment by danysousa** [comment]
AhAh ok :)
Swamp is an implementation of Wamp v2...

**But** I know this error, you can try the 2 following solutions :

> SwampSession.swift with error "fatal error: unexpectedly found nil while unwrapping an Optional value" in this part:
> 
> ``` swift
>     fileprivate func sendMessage(_ message: SwampMessage){
>        let marshalledMessage = message.marshal()
>        let data = self.serializer!.pack(marshalledMessage as [Any])!
>        self.transport.sendData(data)
>    }
> ```

Optional values isn't supported by the apple JSONSerialization class used by Swamp and SwiftyJSON : if you have an optional value in your call arguments (topic name, args, kwargs, etc...), it must be the reason of the crash.

This example create the same crash : 

``` swift
var superList: [Any] = []
var test: String? = "pok"

superList.append(test)
wampSession.call("topicName", args: superList, onSuccess: self.onSuccess, onError: self.onError)
```

If not, check if your Swamp session is connected to the server before the call : 

``` swift
if wampSession.isConnected() {
       wampSession.call("topic_name", args: args)
}
else {
     print("log the error and investigate for know why isn't connected. Are you waiting the SwampSessionDelegate.swampSessionConnected call ?")
}
```

Finaly if you're connected and if you doesn't have any optional value in your arguments, it's a compatibilty problem between Wamp v1 and Wamp v2. Unfortunately for you, Swamp is the only swift framework for WAMP. An Obj-C alternative exist (MDWamp) but it's for WAMP v2 too...

**Comment by dizialina** [comment]
Ok, I'll try to do something with it by using your solutions. Hope it saves me :) Thank you very much for help

**Comment by wybie-lovat** [comment]
It seems like you are using this library against a regular websocket server, and not a WAMP V2 server. Closing.
